content:
  - name: evenements
    label: Événements
    type: collection
    path: content/evenements
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: pages
    label: pages
    type: collection
    path: content
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text

actions:
  - name: deploy-site
    label: Deploy site
    workflow: hugo.yaml